###
POST http://localhost:2007/pelis-plus/users/trending/add HTTP/1.1
Content-Type: application/json

{
  "id": 912520,
  "titulo": "The Nature of Love",
  "año": "2023-09-22",
  "sinopsis": "Sophia is a philosophy professor in Montreal and has lived as a couple with Xavier for 10 years. Sylvain is a carpenter in the Laurentians and must renovate their country house. When Sophia meets Sylvain for the first time, it’s love at first sight. Opposites attract, but can it last?",
  "poster": "/jRaOFDvmrrLmBaCKemQ8Hq9wp5o.jpg",
  "wallpaper": "/qMDPV2FLZfacFgalgqaThMAj47Y.jpg",
  "genre": [10749, 35, 18],
  "duracion": 0,
  "valoracion": 76.37,
  "trailer": null
}


###
GET  http://localhost:2007/pelis-plus/style3 HTTP/1.1

###
GET  http://localhost:2007/pelis-plus/movies/users HTTP/1.1
###
GET  http://localhost:2007/pelis-plus/movies/nowplayin/ HTTP/1.1

###
GET  http://localhost:2007/pelis-plus/users/65b4a17912c35871f804fa01 HTTP/1.1
###

###
GET  http://localhost:2007/pelis-plus/user/franky
###
PUT  http://localhost:2007/pelis-plus/users/65ad4e35730235f4cbac5a80 HTTP/1.1
Content-Type: application/json

{
  "nombre": "nono",
  "edad": "1990-01-01",
  "email": "usuario@example.com",
  "password": "contraseña",
  "saved_movies": ["Pelicula1", "Pelicula2"],
  "liked_movies": ["Pelicula3", "Pelicula4"],
  "saved_series": ["Serie1", "Serie2"],
  "liked_series": ["Serie3", "Serie4"],
  "liked_genres": ["Acción", "Comedia"],
  "icon": "ruta/al/icono.jpg"
}
###
POST  http://localhost:2007/pelis-plus/movies/nowplayin/add HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "titulo": "Pulp Fiction",
  "año": "1994",
  "sinopsis": "La vida de varios criminales se entrelaza en Los Ángeles.",
  "poster": "https://example.com/pulp-fiction-poster.jpg",
  "wallpaper": "https://example.com/pulp-fiction-wallpaper.jpg",
  "genre": ["Crime", "Drama"],
  "duracion": 154,
  "valoracion": 9.0,
  "trailer": "https://example.com/pulp-fiction-trailer"
}


###
DELETE   http://localhost:2007/pelis-plus/movies/nowplayin/delete HTTP/1.1