###
POST http://localhost:2007/pelis-plus/users HTTP/1.1
Content-Type: application/json

{
  "nombre": "NIKOLA TESLA",
  "edad": 30,
  "email": "ION KONWEY@example.com",
  "password": "securepassword",
  "saved_movies": 5,
  "liked_movies": 8,
  "saved_series": 3,
  "liked_series": 6,
  "liked_genres": 10
}
###
GET  http://localhost:2007/pelis-plus/users HTTP/1.1

###
GET  http://localhost:2007/pelis-plus/home HTTP/1.1

###
GET  http://localhost:2007/pelis-plus/users:65ac45b001134daf723a67e3 HTTP/1.1